name: TEST

on: [push]

env:
  APP_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: 1234
          TZ: "Asia/Seoul"

    steps:
      # 파이썬 설정
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # 디펜더시 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      # 테스트
      - name: Test Code
        env:
          TESTING: true
          TELEGRAM_BOT_TOKEN: 123:sometoken
          DB_USERNAME: postgres
          DB_PASSWORD: 1234
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_NAME: postgres
        run: |
          pytest
          zip -r9 report.zip htmlcov/
      # 테스트 결과
      - uses: actions/upload-artifact@v2
        name: Upload Artifact
        with:
          name: REPORT
          path: report.zip
